### ISSUE TITLE
Some models do not have a typically formatted lat/lon gird

### ISSUE THREAD

**Issue by cahartin** [JGCRI/RCMIP5#115]
A few models, in particular MPI-ESM-MR, and MPI-ESM-LR, do not have a typical lat/lon grid.  Both lat/lon vary in both their rows and columns.  In my case, in both the areacello (ocean area) file and then the historical pH file. For now, I am skipping those models/files.  I am not sure how many other models may be odd like this one.

**Comment by bpbond** [comment]
This is really an oddball; Panoply can't load it either.

**Comment by cahartin** [comment]
At least for the `dplyr` version, there's no reason, I (BBL) don't think, that we can't carry around the two-dimensional screwed up grid information of IPSL etc. That is, we could load the lon and lat data directly into the `value` data frame; get rid of the lon and lat members of `cmip5data`; and I think we'd be good.This is probably worth a test.

**Comment by bpbond** [comment]
Fixed in commit 89885f1.
