### ISSUE TITLE
Robustly handling irregular grids

### ISSUE THREAD

**Issue by bpbond** [JGCRI/RCMIP5#120]
For the netcdf files written by CMIP5 models that use regular grids, `lon` and `lat` are small and contain unique values. But for models using non-regular grids, these data are dimensional arrays containing the lon/lat values at each grid point. So we have inconsistent definitions of the `lon` and `lat` fields.

This has a number of consequences; for example, we use expand.grid(lon, lat) in a number of places to generate the full grid, but this is incorrect for irregular grids--should be data.frame(lon, lat). Et cetera.

First task here - probably should have a `regularGrid` flag in the `cmip5data` structure?
Second task - `cmip5data` should be able to generate irregular grids.
Third - test code should test both regular and irregular grids.

**Comment by ktoddbrown** [comment]
I think that yes we should be able to deal with irregular grids. I think this is one of the quirks of the CMIP5 models that we should address in this package.

I don't think that we would need to have a separate flag per say or that cmip5data needs to generate irregular grids (might be useful to throw it into debug list though for dev purposes), although I agree that we need to test both cases.  It's a special case that we should be able to handle but I don't know that we need to 'support' generating irregular grids to that extent.

**Comment by bpbond** [comment]
So how does our code tell, given a `cmip5data` object, whether it's a regular grid or not? The only way I can think of, apart from an explicit flag, is to preserve the 2D `lon` and `lat` arrays (as opposed to the 1D vectors in a regular grid) that are read in from the netcdf. Other suggestions?

**Comment by bpbond** [comment]
In case that last comment wasn't clear: for a regular grid, `x$lon` is exactly as long as the longitude dimension, and has unique values; but for an irregular grid, it has as many elements as there are grid points, giving the longitude value of each, with no uniqueness guarantee. These are quite different, obviously, and the latter will break our current code in many places I think.

**Comment by ktoddbrown** [comment]
Yes, I was thinking of expanding to a 2D lat/lon. Of course the data frame representation doesn't need the additional lat/lon since it's already in the data frame.

I think we would need to rewrite the load and summary functions but everything else should work more or less?

**Comment by bpbond** [comment]
OK, that makes sense and is a straightforward first step: `lon` and `lat` will always be two-dimensional.

**Comment by bpbond** [comment]
How should `filterDimensions` work with irregular grids? Not obvious.

Let's say `x$lon` is 
```
     [,1] [,2]
[1,]   89   90
[2,]  270  271
```

and I do `filterDimensions(x, lons=c(89, 271)`. What should `x$lon` look like afterwards? Have NAs in non-selected spots?

**Comment by ktoddbrown** [comment]
Does it make sense to change filterDimentions to a max/min range instead of an absolute list?

**Comment by bpbond** [comment]
Hi @ktoddbrown I've fixed the nasty load bug and am trying to convert all RCMIP5 code to handle 2D `lon` and `lat` objects - these are necessary to handle irregular grids. Most of this is straightforward, but would you mind taking on `calcGridArea`? You'll see (in the `irregular_fix` branch) that I've only changed the top assertions in the file:

```R
    assert_that(is.matrix(lat))
    assert_that(is.matrix(lon))
```

Anyway, right now it doesn't work correctly with 2D lon/lats, not a surprise. Do you have time to deal with this? Thanks.

**Comment by ktoddbrown** [comment]
I'll take a look at it this afternoon.

**Comment by bpbond** [comment]
Thanks. Both `loadCMIP5` and `cmip5data` correctly (I think) handle 2D lon/lat grids, so you can load/generate sample data using them.

**Comment by ktoddbrown** [comment]
2D lat/lon formats now work with calcGridArea. However I found a but in the as.array conversion. Working on it this evening.

**Comment by ktoddbrown** [comment]
as.array now works as expected. Added a test case in loadCMIP5 to check for this in the future.

**Comment by bpbond** [comment]
You rock. Thanks for the quick turnaround.

**Comment by bpbond** [comment]
Back to the question above: how should `filterDimensions` work with 2D lons and lats? This isn't a problem for the data.frame implementation, as it ignores lon and lat, but what about w.r.t. the array implementation? (This is regardless of whether the filter parameter is a range or a vector.) How do we handle this?

The only thing I can think of is any rows and column that have any value outside of the filter criteria get deleted? That would maintain a rectangular matrix. Other ideas?

**Comment by bpbond** [comment]
@cahartin I've merged the `irregular_fix` branch into `master` for you to update against.

**Comment by cahartin** [comment]
Thank you @bpbond any tests you want me to run?

**Comment by bpbond** [comment]
Commit b6be685 adds support for irregular grids, as well as both the array and data.frame implementations, in `filterDimensions`. In addition, `cmip5data` gets the ability to generate irregular grids, and new test code makes use of this. AFAIK these are the last pieces wrt this issue. Closing.
