### ISSUE TITLE
loadCMIP5 should have a `ZRange` parameter

### ISSUE THREAD

**Issue by bpbond** [JGCRI/RCMIP5#122]
Equivalent to `yearRange`, that lets user only load desired depth values?

Rationale: given the size of CMIP5 files, as much as we can help performance/memory issues by only loading *desired* data, we should.

**Comment by ktoddbrown** [comment]
By that argument maybe we should also have lat/lon ranges as well?

**Comment by bpbond** [comment]
Yeah, probably.

**Comment by bpbond** [comment]
Implemented in commit c44f328.
