### ISSUE TITLE
Need `test_implementations.R`

### ISSUE THREAD

**Issue by bpbond** [JGCRI/RCMIP5#125]
Need to compare results *across* implementations, making sure that they produce the exact same results. Self-assigning.

**Comment by ktoddbrown** [comment]
Along these lines, a data.frame version of regridding needs to be added. It should just be a function of sorting the lat/lon and then apply the same matrix by Z-time slice. I worked up some additional test cases but ran out of time for actual implementation today.

**Comment by bpbond** [comment]
Done in commit 3d757576ea (as part of `test_chainedOperations.R`). Moving @ktoddbrown 's comment above to a new issue and closing this.
