### ISSUE TITLE
Speeding up getProjectionMatrix

### ISSUE THREAD

**Issue by bpbond** [JGCRI/RCMIP5#127]
Test case is the first except `numOrgLon <- 113`, `numOrgLat <- 112`, `numProjLon <- 112` and `numProjLat <- 113`. The first thing I tried is running the function through R's byte code compiler.

Run             | Time (s) 
---------------- | -----------
Original        | 99        
Byte-code compiled | 94 

OK, that's a surprise. Why so little speedup? Where is `getProjectionMatrix` spending its time? Use `Rprof` to get some basic profiling info:

                        total.time | total.pct | self.time | self.pct
-------------------------------- | ----------- | ----------- | -----------
"system.time"             |   89.52 |   100.00    |  0.00  |   0.00
"getProjectionMatrix"  |      89.38   |  99.84   |   5.78  |   6.46
"rbind"                  |    69.56   |  77.70  |   26.78  |  29.92
"anyDuplicated.default"  |    13.52  |   15.10  |   13.52  |  15.10

This is why I put in that line comment on your commit fffacdf; there's a huge penalty when repeatedly `rbind`'ing data frames. I tried writing out those intermediate in-loop data frames to a tempfile, then reading it all back in at the end:

Run             | Time (s) 
---------------- | -----------
Original        | 99        
Bytecode compiled | 94 
Tempfile | 53
Bytecode tempfile | 45

A 2x speedup! Back to the profiler:

                        total.time | total.pct | self.time | self.pct
-------------------------------- | ----------- | ----------- | -----------
"system.time"        |        45.42 |   100.00   |   0.00  |   0.00
"getProjectionMatrix"   |     45.34  |   99.82  |    7.18  |  15.81
"write.table"      |          26.60  |   58.56   |   0.12  |   0.26

At this point there are a number of options for easy further speedup. Using the [readr](http://cran.r-project.org/web/packages/readr/index.html) package would probably give another 2x; or the original `list` and `do.call` method I originally put in, which is all in-memory. (Did that not work?) Anyway I'm going to* commit this current method on master so you can take a look @ktoddbrown .

* commit ab5566d

**Comment by bpbond** [comment]
Update: instead of `do.call` we could use the `dplyr::rbind_all` command, since our package already depends on `dplyr`. Here's the results:


Method             | Time (s) 
---------------- | -----------
Original        | 99        
Bytecode original | 94 
Tempfile | 53
Bytecode tempfile | 45
`rbind_all` | 43
Bytecode `rbind_all` | 43

No compilation improvement at all, and the code is spending the most time in `pmax` and `pmin`, but it's not overwhelming (not shown).

**Comment by ktoddbrown** [comment]
Sold. Nicely done.
