### ISSUE TITLE
RCMIP5 processing error: area files

### ISSUE THREAD

**Issue by cahartin** [JGCRI/RCMIP5#131]
Error: identical(x$lat, area$lat) & identical(x$lon, area$lon) is not TRUE

tos
GISS-E2-R
rcp26

**Comment by cahartin** [comment]
At a second glance it looks like the area file and the data file are not on the same grid. There isn't much we can do, except maybe if it encounters an error like this let it calculate it's own grid areas.

Converting to data frame
CMIP5 data 
Variable: tos (K) from model GISS-E2-R
Data range: 2.7e+02 to 3.1e+02 Mean: 2.9e+02
Experiment: rcp85 - 3 ensemble(s)
Spatial dimensions: lon [144] lat [90] Z [0] 
Time dimension: mon [24] days since 2276-1-1 
Size: 10.9 MB
Provenance has 42 entries
[1] "commuting global mean"
Wed May 27 14:18:06 2015 *** ERROR occurred! **
[1] "Error: identical(x$lat, area$lat) & identical(x$lon, area$lon) is not TRUE\n"

length(oarea$lat)
[1] 51840
> length(oarea$lon)
[1] 51840
> length(d$lat)
[1] 12960
> length(d$lon)
[1] 12960

**Comment by ktoddbrown** [comment]
What is the dim of oarea$lat oarea$lon and d$lat/lon?

**Comment by cahartin** [comment]
dim(oarea$lat)
[1] 288 180
 dim(oarea$lon)
[1] 288 180
 dim(d$lat)
[1] 144  90
 dim(d$lon)
[1] 144  90

**Comment by ktoddbrown** [comment]
Oh wow that's strange. We need to check that it reflects the actual ncdf dimensions but if it's reading it in correctly then I'm comfortable with this error.

**Comment by cahartin** [comment]
Thanks @ktoddbrown  I'll load the files using the regular ncdf package, check the dimensions and let you know what I find.

**Comment by bpbond** [comment]
Haha, wow! Yes, I agree, if real this isn't our fault. Parent script (i.e. ours) can catch that and fall back to a generated grid if necessary.

**Comment by cahartin** [comment]
Yes, looks like the 2 files (area and data) are on different grids, not an error with RCMIP5.  When I load them without the RCMIP5 script, it returns 2 separate dimensions for the area and data files.  Thanks for your help.

**Comment by bpbond** [comment]
Re-opening this to remind me to put in a better error message.
