### ISSUE TITLE
Version 1.2 timing

### ISSUE THREAD

**Issue by bpbond** [JGCRI/RCMIP5#135]
I've added a due date of June 30 for our "v1.2" milestone, aiming to upload RCMIP5 1.2 in July. Is this reasonable and doable? Timeline is totally up to us, of course.

**Comment by cahartin** [comment]
Does that includes the averaged global climate variables?  If so, that should be ok.  I need to process a few more variables to be consistent with the newest package.

**Comment by ktoddbrown** [comment]
I'm good with that. Just coded up an analysis of the land carbon fluxes using RCMIP5, I caught a few edge cases with this that got submitted.

**Comment by cahartin** [comment]
do you think we can push this back a week? I have processed all the data but have not had the chance to format it into the package.

**Comment by bpbond** [comment]
Oh gosh, at least. @ktoddbrown and I have both been otherwise occupied, too. No worries.

**Comment by ktoddbrown** [comment]
Let's revisit this. We need to roll out an update to CRAN in the next two weeks. Are we ready?

**Comment by bpbond** [comment]
Closing this. The two big issues not in this 1.2 update are the dplyr speedup - #140 - and the summarized CMIP data - #129. Bumping them both to 1.3.
