### ISSUE TITLE
INM-CM4 negative C-fluxes

### ISSUE THREAD

**Issue by ktoddbrown** [JGCRI/RCMIP5#136]
Most CMIP5 models have positive primary land carbon fluxes (gpp, rh, ra) except for INM-CM4 which has negative fluxes for some reason. Do we want to catch this in RCMIP5 or leave it as an exercise to the user?

I'm inclined to leave it to the user since there might be other flipped fluxes that we don't run across on the theory that we should 'fix' EVERYTHING or nothing.

**Comment by bpbond** [comment]
Oh god no, that is **not** our problem. Closing this!

**Comment by ktoddbrown** [comment]
Thank you for the laugh :)
