### ISSUE TITLE
ncdf decrepid 

### ISSUE THREAD

**Issue by ktoddbrown** [JGCRI/RCMIP5#144]
Just got the following message:

>This concerns CRAN packages
>
>GhcnDaily SchemaOnRead TSEN boss cruts lgcp marmap meteoForecast qat
>rerddap sirad wux
>
>HelpersMG RCMIP5 bio3d raster rnoaa rworldmap
>
>which depend on package ncdf.  The latter is now deprecated and
>scheduled to be removed from CRAN in Jan 2016.  It has only been keep
>this long because ncdf4 was not available for Windows: it now is (on
>CRAN extras, a default repository for binary installs).

>Please convert your package to use either ncdf4 or RNetCDF as soon as
>possible and definitely by early January.  (For the second group this
>could just mean removing references to ncdf as the package passes its
>checks without it.)

We need to remove ncdf from the package. I'm starting a branch to work on this. Might also be good motivation to finalize vs 1.2 release.

**Comment by bpbond** [comment]
Woo hoo! Oh frabjous day! Good riddance.

**Comment by ktoddbrown** [comment]
@bpbond Indeed :D Can you check out the pull request that I just submitted for this and make sure I didn't break anything? It passes the test files on my end but would be good to get some double checks.

**Comment by bpbond** [comment]
Closing this, as `ncdf` is removed.
