### ISSUE TITLE
saveNetCDF broken?

### ISSUE THREAD

**Issue by aridus** [JGCRI/RCMIP5#149]
Hello

I am trying to use saveNetCDF, thus:

saveNetCDF(loadCMIP5(
  variable = "rhs", 
  model = "HadGEM2-ES", 
  experiment = "rcp26", 
  recursive = FALSE, 
  FUN  =mean), 
verbose = TRUE)

but it consistently returns

Error: !is.null(x$calendarStr) is not TRUE

loadCMIP5 works fine.

I have tried with other variables but always receive the same error.

Thank you.

**Comment by bpbond** [comment]
Hi @aridus - sorry about this. We haven't really done any development on this for a while, but I will try to take a look this weekend and see if I can isolate what's wrong.

**Comment by aridus** [comment]
Thank you, any help would be appreciated!

**Comment by bpbond** [comment]
You're trying to read a file like `rhs_day_HadGEM2-ES_rcp26_r1i1p1_20051201-20151130.nc`? I don't have easy access to this for testing. Can I get that from you (via Dropbox, etc.), if possible? Thanks.

**Comment by aridus** [comment]
Sorry to be slow responding. Thank you, and I have now shared a file at https://www.dropbox.com/s/g0h8awg8tthbqhy/rhs_day_GFDL-ESM2M_rcp60_r1i1p1_20460101-20501231.nc?dl=0

It is large (c. 95 MB).

With grateful thanks.

**Comment by bpbond** [comment]
Hi @aridus - I've opened a PR (#150 ) that fixes this problem. As soon as it's merged, you can `devtools::install_github("JGCRI/RCMIP5")` to get the updated version.
