### ISSUE TITLE
calcGridCell polar centers

### ISSUE THREAD

**Issue by ktoddbrown** [JGCRI/RCMIP5#80]
We should deal gracefully with polar centers (ie abs(lat) == 90). Right now we just error out but we could shift the grid cell to 3/4 of the distance between the nearest neighbor and the pole.

**Comment by bpbond** [comment]
@ktoddbrown Did I see that this was fixed in a recent commit? If so can you comment/close this issue?

**Comment by ktoddbrown** [comment]
We check for polar coordinates and impose those as hard end points in calcGridArea. I'm not happy with it since CMIP5 supposedly reports the mid points of their grid coordinates but yes, this is done.
